# kustomize/overlays/qa/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: single-bpmn-ns                    # ← same namespace

helmCharts:
  - name: foundations-chart
    repo: http://nexus-nexus-repository-manager.default.svc.cluster.local:8081/repository/helm-hosted/
    version: 0.1.0
    releaseName: foundations-qa            # ← different releaseName
    valuesFile: values-foundations-qa.yaml

  - name: job-chart
    repo: http://nexus-nexus-repository-manager.default.svc.cluster.local:8081/repository/helm-hosted/
    version: 0.5.0
    releaseName: foundations-job-qa
    valuesFile: values-job-qa.yaml