# kustomize/overlays/qa/values-foundations-qa.yaml
env: qa
configMapName: "foundations-management-app-cm"
artifactName: "foundations-management-qa-v1.0.0.bpmn"
artifactSha256: "chaning foundations qa"
artifactUrl: "https://nexus/foundations/qa/v1.0.0.bpmn"
