# kustomize/overlays/qa/values-job-qa.yaml
jobName: "claims-bpmn-sync-job-qa"
configMapName: "claims-management-app-cm-qa"    # matches configmap name + env
image: "alpine:3.20"
ttlSecondsAfterFinished: 400
activeDeadlineSeconds: 600
backoffLimit: 1
secretName: "qa-secret"