# kustomize/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: single-bpmn-ns                    # ← single shared namespace, same for all envs

helmCharts:
  - name: foundations-chart
    repo: http://nexus-nexus-repository-manager.default.svc.cluster.local:8081/repository/helm-hosted/
    version: 0.1.0
    releaseName: foundations-dev           # ← releaseName scoped per env
    valuesFile: values-foundations-dev.yaml

  - name: job-chart
    repo: http://nexus-nexus-repository-manager.default.svc.cluster.local:8081/repository/helm-hosted/
    version: 0.5.0
    releaseName: foundations-job-dev              # ← releaseName scoped per env
    valuesFile: values-job-dev.yaml