# kustomize/overlays/dev/values-foundations-dev.yaml
env: dev
configMapName: "foundations-management-app-cm"
artifactName: "foundations-management-dev-v1.0.0.bpmn"
artifactSha256: "changing foundations dev"
artifactUrl: "https://nexus/foundations/dev/v1.0.0.bpmn"
