# apps/claims-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: claims-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # child apps sync after parent
spec:
  project: default

  source:
    repoURL: https://github.com/selflearner2025/helm-with-kustomize.git
    targetRevision: test
    path: kustomize/overlays/dev        # ← points to dev overlay

  destination:
    server: https://kubernetes.default.svc
    namespace: camunda                  # ← shared namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true